language: python
python:
    - "2.6"
    - "2.7"
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libhdf5-serial-dev
install: "pip install -r requirements.txt"
script: "python setup.py test"
